name: Rebuild Docker on Commit

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: windows-10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ danglong7802 }}  # Your Docker Hub username
          password: ${{ danklonk7802 }}  # Your Docker Hub password or personal access token
      
      - name: Build Docker image
        run: docker build -t elearning .  # Replace 'your-image-name' with your actual image name
